# 0. install
# 1. lint
# 2. jest
# 3. write test result

name: CI

on:
  workflow_dispatch:
#  pull_request:
#    branches:
#      - epic/**
#      - develop
#      - main

jobs:
  job-install:
    name: Install dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current commit (${{ github.sha }})
        uses: actions/checkout@v3

      - name: Caching dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-

      - name: Install Dependencies
        if: steps.cache-dependencies.output.cache-hit != 'true'
        run: npm install


  job-lint:
    name: Lint
    needs: job-install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current commit (${{ github.sha }})
        uses: actions/checkout@v3

      - name: Check dependencies cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-

      - name: Run Lint
        run: npm run lint


  job-test:
    name: Test
    needs: job-install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current commit (${{ github.sha }})
        uses: actions/checkout@v3

      - name: Check dependencies cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-

      - name: Run Test
        uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          skip-step: install
          output: report-markdown

#      - name: Report Coverage
#        uses: marocchino/sticky-pull-request-comment@v2
#        with:
#          # pass output from the previous step by id.
#          message: ${{ steps.coverage.outputs.report }}



